# Generated by Django 3.2 on 2021-04-13 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('role_ID', models.AutoField(primary_key=True, serialize=False)),
                ('role_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=250, unique=True)),
                ('password', models.CharField(max_length=250)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobileNo', models.CharField(max_length=15)),
                ('gender', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=15)),
                ('state', models.CharField(max_length=15)),
                ('Country', models.CharField(max_length=15)),
                ('zipCode', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('role_Id', models.ForeignKey(db_column='role_Id', on_delete=django.db.models.deletion.CASCADE, related_name='role_Id', to='User.role')),
            ],
        ),
    ]
